# Generated by Django 2.2 on 2020-09-27 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('000eaf7b-50ad-4728-86a5-c2330e8489d4'), primary_key=True, serialize=False),
        ),
    ]
