# Generated by Django 2.2 on 2021-03-22 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('b8614271-d59e-4411-b3c8-0b43596226da')),
        ),
    ]
