# Generated by Django 2.2 on 2020-09-21 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.UUID('5062dbd6-f453-4af7-b6be-43b2d5c61dce'), primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
