# Generated by Django 2.2 on 2020-09-28 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('eb41280b-3026-4cdb-9971-8dfee6428711'), primary_key=True, serialize=False),
        ),
    ]
