# Generated by Django 2.2 on 2020-09-25 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_plan',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('bdc94e16-141c-46ac-8b7b-d029c83544df'), primary_key=True, serialize=False),
        ),
    ]
