# Generated by Django 2.2 on 2020-10-05 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200928_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('4866366f-9d08-41a7-86a2-e42fa1d00f25'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('Drivers License', 'Drivers License'), ('US Passort/Card', 'US Passort/Card'), ('US Military Card', 'US Military Card'), ('Military Dependents Card', 'Military Dependents Card'), ('Permananet Resident Card', 'Permananet Resident Card'), ('Certificate of Citizenship', 'Certificate of Citizenship'), ('Certificate of Naturalization', 'Certificate of Naturalization'), ('Employment Authorization Document', 'Employment Authorization Document'), ('Foreign Passport', 'Foreign Passport')], max_length=100),
        ),
    ]
