# Generated by Django 2.2 on 2020-09-27 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200927_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a7766e53-d80f-42de-b8c9-a73780fa831a'), primary_key=True, serialize=False),
        ),
    ]
